### ISSUE TITLE
In short, it hangs on the initial loading screen

### ISSUE THREAD

**Issue by eusouofatima** [FullFrontalFrog/OhSoHeroTracker#62] opened 2023-04-11 21:32 UTC
For a while I normally played the free version of 0.18.5 but when I found out about the free 0.19 I downloaded it and installed it and ran it on the computer but every time I started a new one the cutscene does not skip and when it ends the screen is frozen on the loading screen I I tried everything but nothing worked so I came here to ask for help (Note: the file I downloaded didn't come with setup but with the exe,''ohSoHero_Data', some dlls and UnityCrashHandler64).
THANK YOU FOR YOUR ATTENTION.

**Comment by FullFrontalFrog** [comment] 2023-04-11 21:50
Thanks for reporting this. Can you please provide some system info and/or an error log? You can find them here: https://wiki.ohsohero.com/error_logs

We've gotten reports like this from one or more other people but haven't been able to replicate the issue, so we're trying to collect as much data as we can to find out the cause of the problem.

**Comment by MagLjudik** [comment] 2023-06-14 18:03
I still can't replicate this one and there were no logs provided to clarify the error 🤔

**Comment by FullFrontalFrog** [comment] 2024-02-05 15:10
Not able to reproduce this and no leads to go on. I'm going to close this issue.

@eusouofatima If you are able to replicate this on a newer version of the game and can provide logs, feel free to reopen this issue or contact us! Cheers~

**Closed as not planned by FullFrontalFrog** 2024-02-05 15:10 UTC
Labels: bug, cannot replicate
